(()=>{
const $=s=>document.querySelector(s),NS="http://www.w3.org/2000/svg",key="day-window-v3";
const palette=["#2F6DF6","#8B5CF6","#EC4899","#EF4444","#F97316","#F59E0B","#84CC16","#22C55E","#10B981","#14B8A6","#06B6D4","#0EA5E9","#3B82F6","#6366F1","#A855F7","#D946EF","#F43F5E","#E11D48","#FB7185","#FB923C","#FBBF24","#A3E635","#4ADE80","#34D399","#2DD4BF","#22D3EE","#38BDF8","#60A5FA","#818CF8","#C084FC","#E879F9","#F472B6","#F87171","#FDBA74","#FACC15","#94A3B8"];
let blocks=[],showNow=true,timeFormat="24h",appearance="clock",nextColor=0,periodBase=0;
let start=0,end=0,hasSelection=false,editing=null,gesture=null;
const e={dial:$("#dial"),ticks:$("#ticks"),nums:$("#nums"),savedArcs:$("#savedArcs"),preview:$("#previewArc"),ghost:$("#ghostLine"),sh:$("#startHandle"),eh:$("#endHandle"),hint:$("#gestureHint"),add:$("#addDial"),title:$("#title"),range:$("#range"),duration:$("#duration"),editLabel:$("#editLabel"),format12:$("#format12"),format24:$("#format24"),minimal:$("#minimal"),clock:$("#clock"),periodRow:$("#periodRow"),am:$("#am"),pm:$("#pm"),clear:$("#clear"),statusText:$("#statusText"),segments:$("#segments"),scheduled:$("#scheduled"),open:$("#open"),blocks:$("#blocks"),gaps:$("#gaps"),showNow:$("#showNow"),nowLine:$("#nowLine"),nowDot:$("#nowDot"),jumpNow:$("#jumpNow")};
const pad=n=>String(n).padStart(2,"0"),snap5=n=>Math.round(n/5)*5;
function currentColor(){if(editing){const b=blocks.find(x=>x.id===editing);if(b?.color)return b.color}return palette[nextColor%palette.length]}
function applyColor(){document.documentElement.style.setProperty("--current",currentColor())}
function fmt(t,period=true){t=((t%1440)+1440)%1440;const h24=Math.floor(t/60),m=t%60;if(timeFormat==="24h")return `${pad(h24)}:${pad(m)}`;const ap=h24>=12?"PM":"AM";let h=h24%12;if(!h)h=12;return `${h}:${pad(m)}${period?" "+ap:""}`}
function duration(a,b){let d=b-a;if(d<=0)d+=1440;return d}
function fmtDur(m){const h=Math.floor(m/60),r=m%60;return `${h?h+"h":""}${h&&r?" ":""}${r?r+"m":""}`||"0m"}
function spanMinutes(){return timeFormat==="24h"?1440:720}
function faceMinute(t){return timeFormat==="24h"?((t%1440)+1440)%1440:((t%720)+720)%720}
function angleFor(t){return faceMinute(t)/spanMinutes()*Math.PI*2-Math.PI/2}
function pointFor(t,r=151){const a=angleFor(t);return{x:200+Math.cos(a)*r,y:200+Math.sin(a)*r}}
function arcPathByMinutes(a,b,r=178){const span=spanMinutes(),fa=faceMinute(a),fb=faceMinute(b),p1=pointFor(a,r),p2=pointFor(b,r);let diff=(fb-fa+span)%span;if(diff===0&&a!==b)diff=span;return `M ${p1.x} ${p1.y} A ${r} ${r} 0 ${diff>span/2?1:0} 1 ${p2.x} ${p2.y}`}
function splitBlockForFace(b){if(timeFormat==="24h")return [[b.start,b.end]];const d=duration(b.start,b.end);if(d>=720)return [[b.start,b.start+719.999]];return [[b.start,b.end]]}
function saveLocal(){localStorage.setItem(key,JSON.stringify({blocks,showNow,timeFormat,appearance,nextColor,periodBase}))}
function load(){try{const d=JSON.parse(localStorage.getItem(key)||"{}");if(Array.isArray(d.blocks))blocks=d.blocks;if(typeof d.showNow==="boolean")showNow=d.showNow;if(["12h","24h"].includes(d.timeFormat))timeFormat=d.timeFormat;if(["minimalist","clock"].includes(d.appearance))appearance=d.appearance;if(Number.isInteger(d.nextColor))nextColor=d.nextColor;if(d.periodBase===720)periodBase=720}catch{}blocks=blocks.map((b,i)=>({...b,color:b.color||palette[i%palette.length]}));if(!nextColor)nextColor=blocks.length;e.showNow.checked=showNow}
function makeLine(x1,y1,x2,y2,major,opacity){const l=document.createElementNS(NS,"line");for(const [k,v] of Object.entries({x1,y1,x2,y2}))l.setAttribute(k,v);l.setAttribute("stroke",major?"var(--text)":"var(--muted)");l.setAttribute("stroke-width",major?2:0.8);l.setAttribute("opacity",opacity);return l}
function renderFace(){e.ticks.innerHTML="";e.nums.innerHTML="";const span=spanMinutes();if(appearance==="clock"){
  const step=timeFormat==="24h"?5:5;
  for(let m=0;m<span;m+=step){const a=m/span*Math.PI*2-Math.PI/2;const hour=m%60===0,half=m%30===0;const r2=165,r1=hour?150:half?155:160;const op=hour?.68:half?.40:.20;e.ticks.appendChild(makeLine(200+Math.cos(a)*r1,200+Math.sin(a)*r1,200+Math.cos(a)*r2,200+Math.sin(a)*r2,hour,op))}
 }
 if(timeFormat==="24h"){
   const nums=appearance==="clock"?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]:[0,6,12,18];
   nums.forEach(n=>{const a=n/24*Math.PI*2-Math.PI/2,r=appearance==="clock"?121:122,t=document.createElementNS(NS,"text");t.setAttribute("x",200+Math.cos(a)*r);t.setAttribute("y",200+Math.sin(a)*r+4);t.setAttribute("text-anchor","middle");t.setAttribute("font-size",appearance==="clock"?11.5:17);t.setAttribute("font-weight",appearance==="clock"?700:850);t.setAttribute("fill","var(--text)");t.textContent=pad(n);e.nums.appendChild(t)})
 }else{
   const nums=appearance==="clock"?[12,1,2,3,4,5,6,7,8,9,10,11]:[12,3,6,9];
   nums.forEach((n,i)=>{const a=i/12*Math.PI*2-Math.PI/2,r=appearance==="clock"?118:122,t=document.createElementNS(NS,"text");t.setAttribute("x",200+Math.cos(a)*r);t.setAttribute("y",200+Math.sin(a)*r+5);t.setAttribute("text-anchor","middle");t.setAttribute("font-size",appearance==="clock"?17:18);t.setAttribute("font-weight","750");t.setAttribute("fill","var(--text)");t.textContent=n;e.nums.appendChild(t)})
 }
 e.format12.classList.toggle("on",timeFormat==="12h");e.format24.classList.toggle("on",timeFormat==="24h");e.minimal.classList.toggle("on",appearance==="minimalist");e.clock.classList.toggle("on",appearance==="clock");e.periodRow.classList.toggle("hidden",timeFormat==="24h");e.am.classList.toggle("on",periodBase===0);e.pm.classList.toggle("on",periodBase===720)
}
function renderSavedArcs(){e.savedArcs.innerHTML="";blocks.forEach((b,i)=>{splitBlockForFace(b).forEach(([a,z])=>{const p=document.createElementNS(NS,"path");p.setAttribute("d",arcPathByMinutes(a,z,178));p.setAttribute("fill","none");p.setAttribute("stroke",b.color||palette[i%palette.length]);p.setAttribute("stroke-width","9");p.setAttribute("stroke-linecap","round");p.setAttribute("opacity",editing===b.id?"1":".84");e.savedArcs.appendChild(p)})})}
function setHint(mode){e.hint.className="gestureHint"+(mode?" "+mode:"");if(mode==="armed"){e.hint.innerHTML="<strong>Keep dragging</strong><span>Recording starts when you touch the outer ring.</span>"}else if(mode==="recording"){e.hint.innerHTML=`<strong>${fmtDur(duration(start,end))}</strong><span>${fmt(start)} → ${fmt(end)}</span>`}else if(hasSelection){e.hint.innerHTML=`<strong>${fmtDur(duration(start,end))}</strong><span>Tap + to save, or drag again to replace.</span>`}else{e.hint.innerHTML="<strong>Drag outward</strong><span>Start anywhere inside. Recording begins when you reach the outer ring.</span>"}}
function renderSelection(){applyColor();if(!hasSelection){e.preview.setAttribute("d","");e.sh.setAttribute("opacity","0");e.eh.setAttribute("opacity","0");e.add.disabled=true;e.range.textContent="Drag out to select";e.duration.textContent="—";setHint(gesture?.mode==="arming"?"armed":"");return}e.preview.setAttribute("d",arcPathByMinutes(start,end,178));const a=pointFor(start,178),b=pointFor(end,178);e.sh.setAttribute("transform",`translate(${a.x} ${a.y})`);e.eh.setAttribute("transform",`translate(${b.x} ${b.y})`);e.sh.setAttribute("opacity","1");e.eh.setAttribute("opacity","1");e.add.disabled=false;e.range.textContent=`${fmt(start)} – ${fmt(end)}`;e.duration.textContent=fmtDur(duration(start,end));setHint(gesture?.mode==="recording"?"recording":"")}
function pointFromEvent(ev){const r=e.dial.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width*400,y=(ev.clientY-r.top)/r.height*400,dx=x-200,dy=y-200;return{x,y,radius:Math.hypot(dx,dy),angle:(()=>{let a=Math.atan2(dy,dx)+Math.PI/2;if(a<0)a+=Math.PI*2;return a})()}}
function rawFaceMinutes(p){return snap5(p.angle/(Math.PI*2)*spanMinutes())%spanMinutes()}
function startFromPoint(p){const local=rawFaceMinutes(p);return timeFormat==="24h"?local:(periodBase+local)%1440}
function clockwiseEndFromPoint(p){const span=spanMinutes(),localStart=faceMinute(start),localEnd=rawFaceMinutes(p);let diff=(localEnd-localStart+span)%span;if(diff===0)diff=5;if(timeFormat==="24h")return(start+diff)%1440;return(start+diff)%1440}
function beginGesture(ev){const p=pointFromEvent(ev);if(p.radius>128)return false;gesture={pointerId:ev.pointerId,mode:"arming"};e.dial.setPointerCapture(ev.pointerId);e.ghost.setAttribute("opacity",".28");e.ghost.setAttribute("x2",p.x);e.ghost.setAttribute("y2",p.y);setHint("armed");return true}
function moveGesture(ev){if(!gesture||gesture.pointerId!==ev.pointerId)return;const p=pointFromEvent(ev);e.ghost.setAttribute("x2",p.x);e.ghost.setAttribute("y2",p.y);if(gesture.mode==="arming"&&p.radius>=150){gesture.mode="recording";start=startFromPoint(p);end=(start+5)%1440;hasSelection=true;editing=null;e.title.value="";if(navigator.vibrate)navigator.vibrate(8)}else if(gesture.mode==="recording"){end=clockwiseEndFromPoint(p)}renderSelection()}
function endGesture(ev){if(!gesture||gesture.pointerId!==ev.pointerId)return;e.ghost.setAttribute("opacity","0");if(gesture.mode==="arming"){hasSelection=false}gesture=null;renderSelection()}
function split(b){return b.end>b.start?[[b.start,b.end]]:[[b.start,1440],[0,b.end]]}
function union(){const a=blocks.flatMap(split).sort((x,y)=>x[0]-y[0]),out=[];for(const i of a){if(!out.length||i[0]>out[out.length-1][1])out.push([...i]);else out[out.length-1][1]=Math.max(out[out.length-1][1],i[1])}return out}
function gaps(){const u=union(),g=[];if(!u.length)return[[0,1440]];if(u[0][0]>0)g.push([0,u[0][0]]);for(let i=0;i<u.length-1;i++)if(u[i][1]<u[i+1][0])g.push([u[i][1],u[i+1][0]]);if(u.at(-1)[1]<1440)g.push([u.at(-1)[1],1440]);return g}
function renderTimeline(){e.segments.innerHTML="";blocks.forEach(b=>split(b).forEach(([a,z])=>{const d=document.createElement("div");d.className="segBlock";d.style.left=`${a/1440*100}%`;d.style.width=`${Math.max((z-a)/1440*100,.45)}%`;d.style.background=`${b.color}33`;d.style.border=`1px solid ${b.color}`;d.title=`${b.title}: ${fmt(b.start)} – ${fmt(b.end)}`;e.segments.appendChild(d)}));const used=union().reduce((s,[a,z])=>s+z-a,0);e.scheduled.textContent=fmtDur(used);e.open.textContent=fmtDur(1440-used)}
function renderBlocks(){e.blocks.innerHTML="";if(!blocks.length){e.blocks.innerHTML='<div class="empty">No blocks yet. Drag from the center to the outside ring, then tap +.</div>';return}blocks.slice().sort((a,b)=>a.start-b.start).forEach(b=>{const row=document.createElement("div");row.className="row";const main=document.createElement("div");main.innerHTML=`<div class="rowTitle"><span class="dot"></span><span class="name"></span></div><div class="rowTime">${fmt(b.start)} – ${fmt(b.end)} · ${fmtDur(duration(b.start,b.end))}</div>`;main.querySelector(".dot").style.background=b.color;main.querySelector(".name").textContent=b.title||"Untitled block";const acts=document.createElement("div");acts.className="rowActions";const edit=document.createElement("button"),del=document.createElement("button");edit.className=del.className="icon";edit.type=del.type="button";edit.textContent="✎";del.textContent="×";edit.onclick=()=>editBlock(b.id);del.onclick=()=>deleteBlock(b.id);acts.append(edit,del);row.append(main,acts);e.blocks.appendChild(row)})}
function renderGaps(){e.gaps.innerHTML="";const gs=gaps();if(!gs.length){e.gaps.innerHTML='<div class="empty">No open time left in this day.</div>';return}gs.forEach(([a,z])=>{const r=document.createElement("div");r.className="gapRow";r.innerHTML=`<span>${fmt(a)} – ${z===1440?fmt(0):fmt(z)}</span><strong>${fmtDur(z-a)}</strong>`;e.gaps.appendChild(r)})}
function renderAll(){renderFace();renderSavedArcs();renderSelection();renderTimeline();renderBlocks();renderGaps();updateNow();e.statusText.textContent=editing?"Editing block color":"Next block color";e.editLabel.textContent=editing?"Editing block":"New block"}
function addBlock(){if(!hasSelection)return;const title=(e.title.value||"Untitled block").trim().slice(0,40),old=editing?blocks.find(b=>b.id===editing):null,data={id:editing||String(Date.now()),title,start,end,color:old?.color||palette[nextColor%palette.length]};if(editing){const i=blocks.findIndex(b=>b.id===editing);if(i>=0)blocks[i]=data}else{blocks.push(data);nextColor=(nextColor+1)%palette.length}editing=null;hasSelection=false;e.title.value="";saveLocal();renderAll()}
function editBlock(id){const b=blocks.find(x=>x.id===id);if(!b)return;editing=b.id;start=b.start;end=b.end;hasSelection=true;e.title.value=b.title;periodBase=b.start>=720?720:0;window.scrollTo({top:0,behavior:"smooth"});renderAll()}
function deleteBlock(id){blocks=blocks.filter(b=>b.id!==id);if(editing===id){editing=null;hasSelection=false;e.title.value=""}saveLocal();renderAll()}
function clearAll(){if(!blocks.length&&!hasSelection)return;if(confirm("Clear every block in Day Window V3?")){blocks=[];editing=null;hasSelection=false;nextColor=0;e.title.value="";saveLocal();renderAll()}}
function setFormat(v){timeFormat=v;if(v==="12h"&&hasSelection)periodBase=start>=720?720:0;saveLocal();renderAll()}
function setAppearance(v){appearance=v;saveLocal();renderAll()}
function setPeriod(v){periodBase=v;if(hasSelection&&timeFormat==="12h"){const oldStart=start,oldDur=duration(start,end);start=(periodBase+faceMinute(start))%1440;end=(start+Math.min(oldDur,719))%1440;if(oldStart===start)end=(start+oldDur)%1440}saveLocal();renderAll()}
function updateNow(){const n=new Date(),m=n.getHours()*60+n.getMinutes(),left=m/1440*100;[e.nowLine,e.nowDot].forEach(x=>{x.style.left=`${left}%`;x.style.display=showNow?"block":"none"});e.jumpNow.textContent=fmt(m)}
function jumpNow(){const n=new Date(),m=snap5(n.getHours()*60+n.getMinutes())%1440;start=m;end=(m+60)%1440;hasSelection=true;editing=null;periodBase=m>=720?720:0;e.title.value="";window.scrollTo({top:0,behavior:"smooth"});renderAll()}
e.format12.onclick=()=>setFormat("12h");e.format24.onclick=()=>setFormat("24h");e.minimal.onclick=()=>setAppearance("minimalist");e.clock.onclick=()=>setAppearance("clock");e.am.onclick=()=>setPeriod(0);e.pm.onclick=()=>setPeriod(720);e.add.onclick=addBlock;e.clear.onclick=clearAll;e.jumpNow.onclick=jumpNow;e.showNow.onchange=()=>{showNow=e.showNow.checked;saveLocal();updateNow()};
e.dial.addEventListener("pointerdown",ev=>{if(ev.pointerType==="mouse"&&ev.button!==0)return;beginGesture(ev)});e.dial.addEventListener("pointermove",moveGesture);e.dial.addEventListener("pointerup",endGesture);e.dial.addEventListener("pointercancel",endGesture);
load();renderAll();setInterval(updateNow,30000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();