(()=>{
const $=s=>document.querySelector(s),NS="http://www.w3.org/2000/svg",key="day-window-v2";
const palette=["#2F6DF6","#8B5CF6","#EC4899","#EF4444","#F97316","#F59E0B","#84CC16","#22C55E","#10B981","#14B8A6","#06B6D4","#0EA5E9","#3B82F6","#6366F1","#A855F7","#D946EF","#F43F5E","#E11D48","#FB7185","#FB923C","#FBBF24","#A3E635","#4ADE80","#34D399","#2DD4BF","#22D3EE","#38BDF8","#60A5FA","#818CF8","#C084FC","#E879F9","#F472B6","#F87171","#FDBA74","#FACC15","#94A3B8"];
let start=780,end=930,active="start",editing=null,drag=false,blocks=[],showNow=true,timeFormat="12h",appearance="clock",nextColor=0;
const e={dial:$("#dial"),arc:$("#arc"),line:$("#line"),nums:$("#nums"),ticks:$("#ticks"),savedArcs:$("#savedArcs"),sh:$("#startHandle"),eh:$("#endHandle"),startTab:$("#startTab"),endTab:$("#endTab"),startText:$("#startText"),endText:$("#endText"),range:$("#range"),duration:$("#duration"),am:$("#am"),pm:$("#pm"),title:$("#title"),save:$("#save"),newBtn:$("#new"),editLabel:$("#editLabel"),segments:$("#segments"),scheduled:$("#scheduled"),open:$("#open"),blocks:$("#blocks"),gaps:$("#gaps"),showNow:$("#showNow"),nowLine:$("#nowLine"),nowDot:$("#nowDot"),jumpNow:$("#jumpNow"),clear:$("#clear"),format12:$("#format12"),format24:$("#format24"),minimal:$("#minimal"),clock:$("#clock")};
const pad=n=>String(n).padStart(2,"0");
function fmt(t,withPeriod=true){t=((t%1440)+1440)%1440;const h24=Math.floor(t/60),m=t%60;if(timeFormat==="24h")return `${pad(h24)}:${pad(m)}`;const ap=h24>=12?"PM":"AM";let h=h24%12;if(!h)h=12;return `${h}:${pad(m)}${withPeriod?" "+ap:""}`}
function dur(a,b){let d=b-a;if(d<=0)d+=1440;return d}
function fmtDur(m){const h=Math.floor(m/60),r=m%60;return `${h?h+"h":""}${h&&r?" ":""}${r?r+"m":""}`||"0m"}
function polar(t,r=146){const m=((t%720)+720)%720,a=m/720*Math.PI*2-Math.PI/2;return{x:200+Math.cos(a)*r,y:200+Math.sin(a)*r}}
function arcPath(a,b,r=146){const p1=polar(a,r),p2=polar(b,r);let d=((b%720)-(a%720)+720)%720;if(d===0&&a!==b)d=720;return `M ${p1.x} ${p1.y} A ${r} ${r} 0 ${d>360?1:0} 1 ${p2.x} ${p2.y}`}
function saveLocal(){localStorage.setItem(key,JSON.stringify({blocks,showNow,timeFormat,appearance,nextColor}))}
function load(){try{const d=JSON.parse(localStorage.getItem(key)||"{}");if(Array.isArray(d.blocks))blocks=d.blocks;if(typeof d.showNow==="boolean")showNow=d.showNow;if(["12h","24h"].includes(d.timeFormat))timeFormat=d.timeFormat;if(["minimalist","clock"].includes(d.appearance))appearance=d.appearance;if(Number.isInteger(d.nextColor))nextColor=d.nextColor}catch{}blocks=blocks.map((b,i)=>({...b,color:b.color||palette[i%palette.length]}));if(!nextColor)nextColor=blocks.length;e.showNow.checked=showNow}
function blockColor(){if(editing){const b=blocks.find(x=>x.id===editing);if(b?.color)return b.color}return palette[nextColor%palette.length]}
function setActive(v){active=v;e.startTab.classList.toggle("active",v==="start");e.endTab.classList.toggle("active",v==="end");renderEditor()}
function setPeriod(pm){let v=active==="start"?start:end;if((v>=720)!==pm)v+=pm?720:-720;if(active==="start")start=v;else end=v;renderEditor()}
function setFormat(v){timeFormat=v;saveLocal();renderAll()}
function setAppearance(v){appearance=v;saveLocal();renderAll()}
function renderFace(){e.ticks.innerHTML="";e.nums.innerHTML="";if(appearance==="clock"){for(let i=0;i<60;i++){const a=i/60*Math.PI*2-Math.PI/2,major=i%5===0,r1=major?151:158,r2=164,l=document.createElementNS(NS,"line");l.setAttribute("x1",200+Math.cos(a)*r1);l.setAttribute("y1",200+Math.sin(a)*r1);l.setAttribute("x2",200+Math.cos(a)*r2);l.setAttribute("y2",200+Math.sin(a)*r2);l.setAttribute("stroke",major?"var(--text)":"var(--muted)");l.setAttribute("stroke-width",major?2.2:1);l.setAttribute("opacity",major?.55:.3);e.ticks.appendChild(l)}}const vals=appearance==="clock"?[12,1,2,3,4,5,6,7,8,9,10,11]:[12,3,6,9];vals.forEach(n=>{const i=n===12?0:n,a=i/12*Math.PI*2-Math.PI/2,r=appearance==="clock"?112:120,t=document.createElementNS(NS,"text");t.setAttribute("x",200+Math.cos(a)*r);t.setAttribute("y",200+Math.sin(a)*r+6);t.setAttribute("text-anchor","middle");t.setAttribute("font-size",appearance==="clock"?18:17);t.setAttribute("font-weight",appearance==="clock"?650:800);t.setAttribute("fill","var(--text)");t.textContent=n;e.nums.appendChild(t)});e.format12.classList.toggle("on",timeFormat==="12h");e.format24.classList.toggle("on",timeFormat==="24h");e.minimal.classList.toggle("on",appearance==="minimalist");e.clock.classList.toggle("on",appearance==="clock");e.am.textContent=timeFormat==="24h"?"00–11":"AM";e.pm.textContent=timeFormat==="24h"?"12–23":"PM"}
function renderSavedArcs(){e.savedArcs.innerHTML="";blocks.forEach((b,i)=>{const p=document.createElementNS(NS,"path");p.setAttribute("d",arcPath(b.start,b.end,176));p.setAttribute("fill","none");p.setAttribute("stroke",b.color||palette[i%palette.length]);p.setAttribute("stroke-width","8");p.setAttribute("stroke-linecap","round");p.setAttribute("opacity",editing===b.id?"1":".88");e.savedArcs.appendChild(p)})}
function renderEditor(){const s=polar(start),z=polar(end),c=active==="start"?s:z;e.sh.setAttribute("transform",`translate(${s.x} ${s.y})`);e.eh.setAttribute("transform",`translate(${z.x} ${z.y})`);e.arc.setAttribute("d",arcPath(start,end));e.arc.setAttribute("stroke",blockColor());e.line.setAttribute("x2",c.x);e.line.setAttribute("y2",c.y);e.startText.textContent=fmt(start);e.endText.textContent=fmt(end);const same=(start<720)===(end<720);e.range.textContent=timeFormat==="24h"?`${fmt(start)} – ${fmt(end)}`:`${same?fmt(start,false):fmt(start)} – ${fmt(end)}`;e.duration.textContent=fmtDur(dur(start,end));const v=active==="start"?start:end,pm=v>=720;e.am.classList.toggle("on",!pm);e.pm.classList.toggle("on",pm);e.editLabel.textContent=editing?"Editing block":"New block";e.save.textContent=editing?"Save changes":"Add block";e.dial.setAttribute("aria-valuetext",`${active} ${fmt(v)}`)}
function pointerM(ev){const r=e.dial.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width*400,y=(ev.clientY-r.top)/r.height*400;let a=Math.atan2(y-200,x-200)+Math.PI/2;if(a<0)a+=Math.PI*2;let m=Math.round(a/(Math.PI*2)*720/5)*5;if(m>=720)m=0;const c=active==="start"?start:end;return m+(c>=720?720:0)}
function pointerUpdate(ev){const v=pointerM(ev);if(active==="start")start=v;else end=v;renderEditor()}
function split(b){return b.end>b.start?[[b.start,b.end]]:[[b.start,1440],[0,b.end]]}
function union(){const a=blocks.flatMap(split).sort((x,y)=>x[0]-y[0]),out=[];for(const i of a){if(!out.length||i[0]>out[out.length-1][1])out.push([...i]);else out[out.length-1][1]=Math.max(out[out.length-1][1],i[1])}return out}
function gaps(){const u=union(),g=[];if(!u.length)return[[0,1440]];if(u[0][0]>0)g.push([0,u[0][0]]);for(let i=0;i<u.length-1;i++)if(u[i][1]<u[i+1][0])g.push([u[i][1],u[i+1][0]]);if(u.at(-1)[1]<1440)g.push([u.at(-1)[1],1440]);return g}
function renderTimeline(){e.segments.innerHTML="";blocks.forEach(b=>split(b).forEach(([a,z])=>{const d=document.createElement("div");d.className="segBlock";d.style.left=`${a/1440*100}%`;d.style.width=`${Math.max((z-a)/1440*100,.45)}%`;d.style.background=`${b.color}32`;d.style.border=`1px solid ${b.color}`;d.title=`${b.title}: ${fmt(b.start)} – ${fmt(b.end)}`;e.segments.appendChild(d)}));const used=union().reduce((s,[a,z])=>s+z-a,0);e.scheduled.textContent=fmtDur(used);e.open.textContent=fmtDur(1440-used)}
function renderBlocks(){e.blocks.innerHTML="";if(!blocks.length){e.blocks.innerHTML='<div class="empty">No blocks yet. Pick a window above and add it.</div>';return}blocks.slice().sort((a,b)=>a.start-b.start).forEach(b=>{const row=document.createElement("div");row.className="row";const main=document.createElement("div");main.innerHTML=`<div class="rowTitle"><span class="dot"></span><span class="name"></span></div><div class="rowTime">${fmt(b.start)} – ${fmt(b.end)} · ${fmtDur(dur(b.start,b.end))}</div>`;main.querySelector(".dot").style.background=b.color;main.querySelector(".name").textContent=b.title||"Untitled block";const acts=document.createElement("div");acts.className="rowActions";const edit=document.createElement("button"),del=document.createElement("button");edit.className=del.className="icon";edit.type=del.type="button";edit.textContent="✎";del.textContent="×";edit.onclick=()=>editBlock(b.id);del.onclick=()=>deleteBlock(b.id);acts.append(edit,del);row.append(main,acts);e.blocks.appendChild(row)})}
function renderGaps(){e.gaps.innerHTML="";const gs=gaps();if(!gs.length){e.gaps.innerHTML='<div class="empty">No open time left in this day.</div>';return}gs.forEach(([a,z])=>{const r=document.createElement("div");r.className="gapRow";r.innerHTML=`<span>${fmt(a)} – ${z===1440?fmt(0):fmt(z)}</span><strong>${fmtDur(z-a)}</strong>`;e.gaps.appendChild(r)})}
function renderAll(){renderFace();renderSavedArcs();renderEditor();renderTimeline();renderBlocks();renderGaps();updateNow()}
function saveBlock(){const title=(e.title.value||"Untitled block").trim().slice(0,40),old=editing?blocks.find(b=>b.id===editing):null,data={id:editing||String(Date.now()),title,start,end,color:old?.color||palette[nextColor%palette.length]};if(editing){const i=blocks.findIndex(b=>b.id===editing);if(i>=0)blocks[i]=data}else{blocks.push(data);nextColor=(nextColor+1)%palette.length}saveLocal();newBlock();renderAll()}
function editBlock(id){const b=blocks.find(x=>x.id===id);if(!b)return;editing=b.id;start=b.start;end=b.end;e.title.value=b.title;active="start";window.scrollTo({top:0,behavior:"smooth"});renderAll()}
function deleteBlock(id){blocks=blocks.filter(b=>b.id!==id);if(editing===id)newBlock();saveLocal();renderAll()}
function newBlock(){editing=null;start=780;end=930;active="start";e.title.value="";renderEditor()}
function updateNow(){const n=new Date(),m=n.getHours()*60+n.getMinutes(),left=m/1440*100;[e.nowLine,e.nowDot].forEach(x=>{x.style.left=`${left}%`;x.style.display=showNow?"block":"none"});e.jumpNow.textContent=fmt(m)}
function jumpNow(){const n=new Date(),m=Math.round((n.getHours()*60+n.getMinutes())/5)*5%1440;start=m;end=(m+60)%1440;active="start";editing=null;e.title.value="";renderEditor();window.scrollTo({top:0,behavior:"smooth"})}
e.format12.onclick=()=>setFormat("12h");e.format24.onclick=()=>setFormat("24h");e.minimal.onclick=()=>setAppearance("minimalist");e.clock.onclick=()=>setAppearance("clock");e.startTab.onclick=()=>setActive("start");e.endTab.onclick=()=>setActive("end");e.am.onclick=()=>setPeriod(false);e.pm.onclick=()=>setPeriod(true);e.save.onclick=saveBlock;e.newBtn.onclick=newBlock;e.jumpNow.onclick=jumpNow;e.showNow.onchange=()=>{showNow=e.showNow.checked;saveLocal();updateNow()};e.clear.onclick=()=>{if(confirm("Clear all blocks in V2?")){blocks=[];editing=null;nextColor=0;saveLocal();renderAll()}};
e.dial.addEventListener("pointerdown",ev=>{drag=true;e.dial.setPointerCapture(ev.pointerId);const target=pointerM(ev),cd=(a,b)=>Math.abs((((a-b)+720)%1440)-720);active=cd(target,start)<=cd(target,end)?"start":"end";setActive(active);pointerUpdate(ev)});e.dial.addEventListener("pointermove",ev=>{if(drag)pointerUpdate(ev)});e.dial.addEventListener("pointerup",()=>drag=false);e.dial.addEventListener("pointercancel",()=>drag=false);e.dial.addEventListener("keydown",ev=>{if(!["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(ev.key))return;ev.preventDefault();const d=(ev.key==="ArrowRight"||ev.key==="ArrowUp")?5:-5;if(active==="start")start=(start+d+1440)%1440;else end=(end+d+1440)%1440;renderEditor()});
load();renderAll();setInterval(updateNow,30000);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
})();